### ISSUE TITLE
Dockerで動かすとError reason=[Errno 32] Broken pipeが発生する

### ISSUE THREAD

**Issue by re3turn** [re3turn/twicrawler#26]
```
app_1       | Error reason=[Errno 32] Broken pipe
app_1       | Traceback (most recent call last):
app_1       |   File "/app/app/crawler.py", line 37, in upload_google_photos
app_1       |     self.google_photos.upload_media(media_path, description)
app_1       |   File "/app/app/google_photos.py", line 86, in upload_media
app_1       |     upload_token = self._execute_upload_api(data=file_data, upload_file_name=os.path.basename(file_path))
app_1       |   File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-4>", line 2, in _execute_upload_api
app_1       |   File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
app_1       |     logger)
app_1       |   File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
app_1       |     return f()
app_1       |   File "/app/app/google_photos.py", line 78, in _execute_upload_api
app_1       |     headers=headers)
app_1       |   File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 198, in request
app_1       |     uri, method, body=body, headers=request_headers, **kwargs)
app_1       |   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1957, in request
app_1       |     cachekey,
app_1       |   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1622, in _request
app_1       |     conn, request_uri, method, body, headers
app_1       |   File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1529, in _conn_request
app_1       |     conn.request(method, request_uri, body, headers)
app_1       |   File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
app_1       |     self._send_request(method, url, body, headers, encode_chunked)
app_1       |   File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
app_1       |     self.endheaders(body, encode_chunked=encode_chunked)
app_1       |   File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
app_1       |     self._send_output(message_body, encode_chunked=encode_chunked)
app_1       |   File "/usr/local/lib/python3.7/http/client.py", line 1065, in _send_output
app_1       |     self.send(chunk)
app_1       |   File "/usr/local/lib/python3.7/http/client.py", line 987, in send
app_1       |     self.sock.sendall(data)
app_1       |   File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall
app_1       |     v = self.send(byte_view[count:])
app_1       |   File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
app_1       |     return self._sslobj.write(data)
app_1       | BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by re3turn** [comment]
close

**Comment by re3turn** [comment]
#28
